global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["hide-seek-server:9999"]
      labels:
        hostname: hide-seek-server-monitoring.game